#
# Include Xilinx common definitions and Lab X AVB headers
#
EXTRA_CFLAGS += -I$(TOPDIR)/drivers/xilinx_common
EXTRA_CFLAGS += -I$(TOPDIR)/drivers/net/labx_avb

# Include the Inferno-specific drivers
obj-y += Inferno_setup.o
obj-y += mv88e6350R.o
