#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
TZ=UTC

echo "Mounting proc, sys, /dev/pts: "
mount -t proc proc /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts

BUTTONS=`tr ' ' '\\n' < /proc/cmdline | grep BUTTONS | cut -d'=' -f2`
export BUTTONS

echo "Configuring devices: "
if [ -d /sys/class/gpio/gpiochip240 ]; then
  OLEDINDEV="247"
  OLEDOUTDEV="246"
  GNETOUTDEV="245"
else
  OLEDINDEV="255"
  OLEDOUTDEV="254"
  GNETOUTDEV="253"
fi
echo -e "${OLEDINDEV}\n${OLEDOUTDEV}\n${GNETOUTDEV}" > /sys/class/gpio/export
echo high > "/sys/class/gpio/gpio${OLEDINDEV}/direction"
echo out > "/sys/class/gpio/gpio${OLEDOUTDEV}/direction"
echo out > "/sys/class/gpio/gpio${GNETOUTDEV}/direction"
echo -en "\x2e\x26\x01\x22\x38\x26\x3e\x2b\x00\x3f\x00\x00\x3f\x00" >/dev/spidev0
echo -en "\x26\x01\x23\x50\x28\x5f\x3f\x18\x0d" > /dev/spidev0
echo -en "\x27\x5e\x00\x0c\x00\x00\x2f" > /dev/spidev0

echo "Mounting var: "
mount -t ramfs none /var

echo "Populating /var: "
mkdir /var/run
mkdir /var/tmp
chmod 1777 /var/tmp
mkdir /var/devices
mkdir /var/devices/gpio
ln -s "/sys/class/gpio/gpio${OLEDINDEV}/value" /var/devices/gpio/oled_in
ln -s "/sys/class/gpio/gpio${OLEDOUTDEV}/value" /var/devices/gpio/oled_out
ln -s "/sys/class/gpio/gpio${GNETOUTDEV}/value" /var/devices/gpio/gnet_out

echo "Restoring persistent settings."
mkdir /var/tmp/persist
touch /var/tmp/persist/environment
/bin/mtd-storage -I /dev/mtd0 -s 0x800000 -e 0xffffff var/tmp/persist
if [ "$BUTTONS" = "0x00" ]; then
  . /var/tmp/persist/environment
fi
echo "Running system startup scripts."
for i in /etc/rc.d/S*
do
  if [ -x $i ]; then
    /bin/sh $i
  fi
done
