#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
TZ=UTC

echo "Mounting proc, sys, /dev/pts: "
mount -t proc proc /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts

BUTTONS=`tr ' ' '\\n' < /proc/cmdline | grep BUTTONS | cut -d'=' -f2`
export BUTTONS
echo "Locking flash:"
/bin/mtd-lock -l -d /dev/mtd0

echo "Configuring devices: "
if [ -d /sys/class/gpio/gpiochip240 ]; then
  OLEDBUTTONDEV="247"
  OLEDDATADEV="246"
  OLEDPOWERDEV="245"
else
  OLEDBUTTONDEV="255"
  OLEDDATADEV="254"
  GNETOUTDEV="253"
fi
if [ ! -z "${OLEDBUTTONDEV}" ]; then
  if [ ! -d "/sys/class/gpio/gpio${OLEDBUTTONDEV}" ]; then
    echo -e "${OLEDBUTTONDEV}"  > /sys/class/gpio/export
  fi
fi
if [ ! -z $OLEDDATADEV ]; then
  if [ ! -d "/sys/class/gpio/gpio${OLEDDATADEV}" ]; then
    echo -e "${OLEDDATADEV}"  > /sys/class/gpio/export
  fi
fi
if [ ! -z $OLEDPOWERDEV ]; then
  if [ ! -d "/sys/class/gpio/gpio${OLEDPOWERDEV}" ]; then
    echo -e "${OLEDPOWERDEV}"  > /sys/class/gpio/export
  fi
fi
if [ ! -z $GNETOUTDEV ]; then
  if [ ! -d "/sys/class/gpio/gpio${GNETOUTDEV}" ]; then
    echo -e "${GNETOUTDEV}"  > /sys/class/gpio/export
  fi
fi
# Output side forced high, then used as an input (OLED Button)
if [ -d "/sys/class/gpio/gpio${OLEDBUTTONDEV}" ]; then
  echo high > "/sys/class/gpio/gpio${OLEDBUTTONDEV}/direction"
  echo in  > "/sys/class/gpio/gpio${OLEDBUTTONDEV}/direction"
fi
if [ -d "/sys/class/gpio/gpio${OLEDDATADEV}" ]; then
  echo low > "/sys/class/gpio/gpio${OLEDDATADEV}/direction"
fi
if [ -d "/sys/class/gpio/gpio${OLEDPOWERDEV}" ]; then
  echo low > "/sys/class/gpio/gpio${OLEDPOWERDEV}/direction"
fi
if [ -d "/sys/class/gpio/gpio${GNETOUTDEV}" ]; then
  echo out > "/sys/class/gpio/gpio${GNETOUTDEV}/direction"
fi
echo -en "\x26\x01\x22\x38\x26\x3e\x2b\x00\x3f\x00\x00\x3f\x00" >/dev/spidev0
echo -en "\x26\x01\x23\x50\x28\x5f\x3f\x18\x0d" > /dev/spidev0

echo "Mounting var: "
mount -t ramfs none /var

echo "Populating /var: "
mkdir /var/run
mkdir /var/tmp
chmod 1777 /var/tmp
mkdir /var/devices
mkdir /var/devices/gpio
if [ -d "/sys/class/gpio/gpio${OLEDBUTTONDEV}" ]; then
  ln -s "/sys/class/gpio/gpio${OLEDBUTTONDEV}/value" /var/devices/gpio/oled_in
fi
if [ -d "/sys/class/gpio/gpio${OLEDDATADEV}" ]; then
  ln -s "/sys/class/gpio/gpio${OLEDDATADEV}/value" /var/devices/gpio/oled_out
fi
if [ -d "/sys/class/gpio/gpio${OLEDPOWERDEV}" ]; then
  ln -s "/sys/class/gpio/gpio${OLEDPOWERDEV}/value" /var/devices/gpio/oled_power
fi
if [ -d "/sys/class/gpio/gpio${GNETOUTDEV}" ]; then
  ln -s "/sys/class/gpio/gpio${GNETOUTDEV}/value" /var/devices/gpio/gnet_out
fi

echo "Restoring persistent settings:"
mkdir /var/tmp/persist
touch /var/tmp/persist/environment
/bin/mtd-storage -I /dev/mtd0 -s 0x800000 -e 0xffffff var/tmp/persist
if [ "$BUTTONS" = "0x00" ]; then
  . /var/tmp/persist/environment
fi
echo "Running system startup scripts:"
for i in /etc/rc.d/S*
do
  if [ -x $i ]; then
    /bin/sh $i
  fi
done
if [ "$BUTTONS" = "0x00" ]; then
  if [ "$DISABLE_ETH1" = "1" ]; then
    ifconfig eth1 down
  fi
  if [ -x /var/tmp/persist/rc.local ]; then
    /bin/sh /var/tmp/persist/rc.local
  fi
fi

