#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define PT_SIZE 152 /* sizeof(struct pt_regs)	 # */
#define PT_MSR 132 /* offsetof(struct pt_regs, msr)	 # */
#define PT_EAR 136 /* offsetof(struct pt_regs, ear)	 # */
#define PT_ESR 140 /* offsetof(struct pt_regs, esr)	 # */
#define PT_FSR 144 /* offsetof(struct pt_regs, fsr)	 # */
#define PT_PC 128 /* offsetof(struct pt_regs, pc)	 # */
#define PT_R0 0 /* offsetof(struct pt_regs, r0)	 # */
#define PT_R1 4 /* offsetof(struct pt_regs, r1)	 # */
#define PT_R2 8 /* offsetof(struct pt_regs, r2)	 # */
#define PT_R3 12 /* offsetof(struct pt_regs, r3)	 # */
#define PT_R4 16 /* offsetof(struct pt_regs, r4)	 # */
#define PT_R5 20 /* offsetof(struct pt_regs, r5)	 # */
#define PT_R6 24 /* offsetof(struct pt_regs, r6)	 # */
#define PT_R7 28 /* offsetof(struct pt_regs, r7)	 # */
#define PT_R8 32 /* offsetof(struct pt_regs, r8)	 # */
#define PT_R9 36 /* offsetof(struct pt_regs, r9)	 # */
#define PT_R10 40 /* offsetof(struct pt_regs, r10)	 # */
#define PT_R11 44 /* offsetof(struct pt_regs, r11)	 # */
#define PT_R12 48 /* offsetof(struct pt_regs, r12)	 # */
#define PT_R13 52 /* offsetof(struct pt_regs, r13)	 # */
#define PT_R14 56 /* offsetof(struct pt_regs, r14)	 # */
#define PT_R15 60 /* offsetof(struct pt_regs, r15)	 # */
#define PT_R16 64 /* offsetof(struct pt_regs, r16)	 # */
#define PT_R17 68 /* offsetof(struct pt_regs, r17)	 # */
#define PT_R18 72 /* offsetof(struct pt_regs, r18)	 # */
#define PT_R19 76 /* offsetof(struct pt_regs, r19)	 # */
#define PT_R20 80 /* offsetof(struct pt_regs, r20)	 # */
#define PT_R21 84 /* offsetof(struct pt_regs, r21)	 # */
#define PT_R22 88 /* offsetof(struct pt_regs, r22)	 # */
#define PT_R23 92 /* offsetof(struct pt_regs, r23)	 # */
#define PT_R24 96 /* offsetof(struct pt_regs, r24)	 # */
#define PT_R25 100 /* offsetof(struct pt_regs, r25)	 # */
#define PT_R26 104 /* offsetof(struct pt_regs, r26)	 # */
#define PT_R27 108 /* offsetof(struct pt_regs, r27)	 # */
#define PT_R28 112 /* offsetof(struct pt_regs, r28)	 # */
#define PT_R29 116 /* offsetof(struct pt_regs, r29)	 # */
#define PT_R30 120 /* offsetof(struct pt_regs, r30)	 # */
#define PT_R31 124 /* offsetof(struct pt_regs, r31)	 # */
#define PT_MODE 148 /* offsetof(struct pt_regs, pt_mode)	 # */

#define PT_TEXT_ADDR 153 /* sizeof(struct pt_regs) + 1	 # */
#define PT_TEXT_LEN 154 /* sizeof(struct pt_regs) + 2	 # */
#define PT_DATA_ADDR 155 /* sizeof(struct pt_regs) + 3	 # */

#define TS_THREAD_INFO 4 /* offsetof(struct task_struct, stack)	 # */
#define TI_TASK 0 /* offsetof(struct thread_info, task)	 # */
#define TI_FLAGS 8 /* offsetof(struct thread_info, flags)	 # */
#define TI_ADDR_LIMIT 24 /* offsetof(struct thread_info, addr_limit)	 # */
#define TI_CPU_CONTEXT 56 /* offsetof(struct thread_info, cpu_context)	 # */

#define CC_R1 0 /* offsetof(struct cpu_context, r1)	 # */
#define CC_R2 4 /* offsetof(struct cpu_context, r2)	 # */
#define CC_R13 8 /* offsetof(struct cpu_context, r13)	 # */
#define CC_R14 12 /* offsetof(struct cpu_context, r14)	 # */
#define CC_R15 16 /* offsetof(struct cpu_context, r15)	 # */
#define CC_R16 20 /* offsetof(struct cpu_context, r16)	 # */
#define CC_R17 24 /* offsetof(struct cpu_context, r17)	 # */
#define CC_R18 28 /* offsetof(struct cpu_context, r18)	 # */
#define CC_R19 32 /* offsetof(struct cpu_context, r19)	 # */
#define CC_R20 36 /* offsetof(struct cpu_context, r20)	 # */
#define CC_R21 40 /* offsetof(struct cpu_context, r21)	 # */
#define CC_R22 44 /* offsetof(struct cpu_context, r22)	 # */
#define CC_R23 48 /* offsetof(struct cpu_context, r23)	 # */
#define CC_R24 52 /* offsetof(struct cpu_context, r24)	 # */
#define CC_R25 56 /* offsetof(struct cpu_context, r25)	 # */
#define CC_R26 60 /* offsetof(struct cpu_context, r26)	 # */
#define CC_R27 64 /* offsetof(struct cpu_context, r27)	 # */
#define CC_R28 68 /* offsetof(struct cpu_context, r28)	 # */
#define CC_R29 72 /* offsetof(struct cpu_context, r29)	 # */
#define CC_R30 76 /* offsetof(struct cpu_context, r30)	 # */
#define CC_MSR 80 /* offsetof(struct cpu_context, msr)	 # */
#define CC_EAR 84 /* offsetof(struct cpu_context, ear)	 # */
#define CC_ESR 88 /* offsetof(struct cpu_context, esr)	 # */
#define CC_FSR 92 /* offsetof(struct cpu_context, fsr)	 # */


#endif
