#!/bin/sh

IP_ADDRESS_A=192.168.1.1
IP_ADDRESS_B=192.168.2.1
IP_ADDRESS_C=192.168.3.1
IP_ADDRESS_D=192.168.4.1

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo "Setting up interface lo: "
ifconfig lo up 127.0.0.1

echo "Setting up interface eth0: "
ifconfig eth0 $IP_ADDRESS_A

echo "Setting up interface eth1: "
ifconfig eth1 $IP_ADDRESS_B

echo "Setting up interface eth2: "
ifconfig eth2 $IP_ADDRESS_C

echo "Setting up interface eth3: "
ifconfig eth3 $IP_ADDRESS_D
