#!/bin/sh

echo "Launching AVB daemon..."

# Look for config file in jffs file system first, then fall back to romfs
XMLFILE=/mnt/config/AvbPlatform.xml
if [ ! -f $XMLFILE ] ; then
  echo "Using platform configuration from ROMfs"
  XMLFILE=/mnt/apps/AvbPlatform.xml
else
  echo "Using platform configuration from JFFS2"
fi

AVBDFILE=/mnt/config/avbd
if [ ! -f $AVBDFILE ] ; then
  echo "Using avbd application from ROMfs"
  AVBDFILE=/mnt/apps/avbd
else
  echo "Using avbd application from JFFS2"
fi

$AVBDFILE platformFile=$XMLFILE &

# If there is an XML file named Config*.xml in /mnt/config, feed it to avb_config to set up streams
AVB_CONFIGFILE=/mnt/apps/avb_config
AVB_CONFIGXML=`ls -1 /mnt/config/Config*.xml 2>/dev/null | head -1`
if [ ! -z "$AVB_CONFIGXML" ] ; then
  sleep 3
  echo "Configuring avbd from $AVB_CONFIGXML"
  $AVB_CONFIGFILE $AVB_CONFIGXML
fi
