#!/bin/sh

# For the moment, simply define static IP addresses
IP_ADDRESS_A=192.168.1.1

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo "Setting up interface lo: "
ifconfig lo up 127.0.0.1

echo "Setting up interface eth0: "
ifconfig eth0 $IP_ADDRESS_A
ifconfig eth0 up

echo "SKIPPING SOME NETWORK!"
mkdir /var/tmp/dhcpc
mkdir /var/lib
mkdir /var/tmp/avahi
mkdir /var/tmp/avahi/services
#/bin/cp /etc/avahi.orig/avahi-daemon.conf /etc/avahi.orig/avahi-autoipd.action  /var/tmp/avahi
#/bin/cp /etc/avahi.orig/services/* /var/tmp/avahi/services/ > /dev/null 2>&1
#/bin/avahi-daemon >/dev/null 2>&1 &
#/bin/dhcpcd -t0 eth0 &
#/bin/avahi-autoipd-wrapper eth0 >/dev/null 2>&1 &
#/bin/inetd &
