#
# Include Xilinx common definitions and Lab X AVB headers
#
EXTRA_CFLAGS += -I$(TOPDIR)/drivers/xilinx_common
EXTRA_CFLAGS += -I$(TOPDIR)/drivers/net/labx_avb

# Include the AES driver and word clock GPIO setup
obj-y += aes3_rx.o
obj-y += wclock_gpio.o
