#
# Include Xilinx common definitions and Lab X AVB headers
#
EXTRA_CFLAGS += -I$(TOPDIR)/drivers/xilinx_common
EXTRA_CFLAGS += -I$(TOPDIR)/drivers/net/labx_avb

# Include the AES driver
obj-y += aes3_rx.o
