#
# Automatically generated make config: don't edit
#

#
# Vendor/Product Selection
#

#
# Select the Vendor you wish to target
#
CONFIG_DEFAULTS_MEYERSOUND=y

#
# Select the Product you wish to target
#
# CONFIG_DEFAULTS_XILINX_ML401 is not set
CONFIG_DEFAULTS_MEYERSOUND_DMITRI_IO=y
# CONFIG_DEFAULTS_XILINX_ML501 is not set
# CONFIG_DEFAULTS_XILINX_ML505 is not set
# CONFIG_DEFAULTS_XILINX_ML505_LL_TEMAC_SGDMA_EDK101 is not set
# CONFIG_DEFAULTS_XILINX_ML505_LL_TEMAC_SGDMA_MMU_EDK101 is not set
# CONFIG_DEFAULTS_XILINX_ML505_MMU is not set
# CONFIG_DEFAULTS_XILINX_ML506 is not set
# CONFIG_DEFAULTS_XILINX_S3DSP1800A_REV1_EDK101 is not set
# CONFIG_DEFAULTS_XILINX_S3DSP1800A_REV1_MMU_EDK101 is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E1600_MMU is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E1600_REVA is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E1600_REVA_LITE_EDK101 is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E1600_REVA_LITE_MMU_EDK101 is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E1600_REVA_SGDMA is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E500_MMU is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E500_REVC is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E500_REVC_LITE_EDK101 is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E500_REVD is not set
# CONFIG_DEFAULTS_XILINX_SPARTAN3E500_REVD_LITE_EDK101 is not set

#
# Kernel/Library/Defaults Selection
#
# CONFIG_DEFAULTS_KERNEL_2_4 is not set
CONFIG_DEFAULTS_KERNEL_2_6=y
# CONFIG_DEFAULTS_LIBC_NONE is not set
CONFIG_DEFAULTS_LIBC_UCLIBC=y
# CONFIG_DEFAULTS_OVERRIDE is not set
# CONFIG_DEFAULTS_KERNEL is not set
# CONFIG_DEFAULTS_VENDOR is not set
# CONFIG_DEFAULTS_VENDOR_UPDATE is not set
CONFIG_VENDOR=MeyerSound
CONFIG_PRODUCT=dmitri-io
CONFIG_LINUXDIR=linux-2.6.x
CONFIG_LIBCDIR=
