#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo "Setting up interface lo: "
ifconfig lo up 127.0.0.1

# For the moment, simply define static IP addresses
IP_ADDRESS_PREFIX=192.168

IS_STAGEBOX=`cat /sys/class/garcia_fpga/jumper1`
if [ $IS_STAGEBOX -eq 0 ] ; then
  ifconfig eth3 $IP_ADDRESS_PREFIX.4.1
  if [ $? -ne 0 ] ; then
    IS_STAGEBOX=1 ;
  else
    ifconfig eth2 $IP_ADDRESS_PREFIX.3.1
    if [ $? -ne 0 ] ; then
      IS_STAGEBOX=1 ;
    else
    fi
  fi
else
  echo "Jumper 1 installed - forcing stage box configuration"
fi
if [ $IS_STAGEBOX -ne 0 ] ; then
  echo stagebox > /var/tmp/role
  if [ `cat /sys/class/garcia_fpga/selector` -eq 5 ] ; then
    ifconfig eth1 $IP_ADDRESS_PREFIX.4.2
    ifconfig eth0 $IP_ADDRESS_PREFIX.3.2
  else
    ifconfig eth1 $IP_ADDRESS_PREFIX.2.2
    ifconfig eth0 $IP_ADDRESS_PREFIX.1.2
  fi
  ifconfig eth2 down 2>/dev/null
  ifconfig eth3 down 2>/dev/null
else
  ifconfig eth1 $IP_ADDRESS_PREFIX.2.1
  ifconfig eth0 $IP_ADDRESS_PREFIX.1.1
  echo console > /var/tmp/role
fi

mkdir /var/tmp/dhcpc
mkdir /var/lib
mkdir /var/tmp/avahi
mkdir /var/tmp/avahi/services
/bin/cp /etc/avahi.orig/avahi-daemon.conf /etc/avahi.orig/avahi-autoipd.action  /var/tmp/avahi
/bin/cp /etc/avahi.orig/services/* /var/tmp/avahi/services/ > /dev/null 2>&1
/bin/avahi-daemon >/dev/null 2>&1 &
/bin/dhcpcd -t0 eth0 &
/bin/avahi-autoipd-wrapper eth0 >/dev/null 2>&1 &
/bin/inetd &
