#!/bin/sh

# Mount the application ROMfs
echo "Mounting application ROMfs image"
mount -t romfs /dev/mtdblock6 /mnt/apps

# Mount the configuration JFFS2
echo "Mounting configuration JFFS2 image"
mount -t jffs2 /dev/mtdblock11 /mnt/config

