#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo "Setting up interface lo: "
ifconfig lo up 127.0.0.1
ifconfig eth0 multicast up
ifconfig eth1 multicast up

mkdir /var/lib
/bin/inetd &

# Call a script located on the read-write Flash filesystem to
# permit users to easily modify the persistent network settings

echo "Calling platform-specific network script"

if [ -x /etc/persist/config/network_config ]
  then
  /etc/persist/config/network_config
  else
  if [ ! -f /etc/persist/config/CAL_ICSPlatform.xml ]
    then
    mkdir /etc/persist/config 2>/dev/null
    cp /etc/config.orig/CAL_ICSPlatform.xml /etc/persist/config/CAL_ICSPlatform.xml
  fi

  XMLFILE=/etc/persist/config/CAL_ICSPlatform.xml
  
  if [ -f /etc/persist/bin/avbd ]
    then
    AVBDFILE=/etc/persist/bin/avbd
    else
    AVBDFILE=/usr/bin/avbd
  fi
  $AVBDFILE platformFile=$XMLFILE &

  if [ -f /etc/persist/bin/avbd ]
    then
    P17221DFILE=/etc/persist/bin/p17221d
    else
    P17221DFILE=/usr/bin/p17221d
  fi
  $P17221DFILE 127.0.0.1 8080 &

fi
