.PHONY : all build romfs clean

build_dir = tmp

all: build
	$(MAKE) -C ${build_dir}

build: Makefile
	rm -rf ${build_dir}
	mkdir ${build_dir}
	(cd ${build_dir}; CFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)" LIBS="$(LDLIBS)" ../configure-microblaze )

romfs:
	(cd $(build_dir); ROMFSINST="$(ROMFSINST)" $(MAKE) romfs)  	

clean:
	rm -rf ${build_dir}

