PROJECT=cal-dsp
PROJECT_NAME=cal-dsp
PROJECT_VERSION=1
PROJECT_EMAIL=andrel@meyersound.com
PROJECT_LICENSE=private
PROJECT_MAINTAINER=andrel@meyersound.com
PROJECT_COPYRIGHT=Copyright 2012
PROJECT_DESCRIPTION=cal-dsp
PROJECT_WEBSITE=https://devel.polaris.msli.com/git/cal-dsp.git
PROJECT_IDENTIFIER=com.meyersound.call.dsp
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
COMPILE_FLAGS+=-Wall -pedantic -std=c99 -Wunused 
PREPROCESS_FLAGS+=-DANDREL_DEVEL


ENABLE_PRECOMPILED_HEADERS?=0

SOFTWARE_LIB_DIR?=$(realpath $(PROJECT_TOP_DIR)/..)
MICROSUPPORT_CONFIG?=$(SOFTWARE_LIB_DIR)/microsupport/microsupport-config

CONFIG_TOOLS+=$(MICROSUPPORT_CONFIG)

