/*
 * garcia_fpga_priv.h
 *
 *  Created on: Jan 25, 2011
 *      Author: swagner
 */
#ifndef GARCIA_FPGA_PRIV_H_
#define GARCIA_FPGA_PRIV_H_

#include <linux/garcia_fpga.h>

#define GARCIA_FPGA_GPIO_REGISTER	0x00
#define GARCIA_FPGA_GPIO_GIER		0x47*4
#define GARCIA_FPGA_GPIO_IPIER		0x4A*4
#define GARCIA_FPGA_GPIO_IPISR		0x48*4

#define GARCIA_FPGA_GPIO_GIE		0x80000000
#define GARCIA_FPGA_GPIO_IPIE		0x1

#define GARCIA_GPIO_INPUTS_MASK ( \
	GARCIA_FPGA_GPIO_BOX_ID_MASK | GARCIA_FPGA_GPIO_PUSHBUTTON | GARCIA_FPGA_GPIO_PWRFAIL | \
	GARCIA_FPGA_GPIO_JUMPER_1 | GARCIA_FPGA_GPIO_JUMPER_2 | GARCIA_FPGA_GPIO_DEBUG_0 | \
	GARCIA_FPGA_GPIO_DEBUG_1 | GARCIA_FPGA_GPIO_DEBUG_2 | GARCIA_FPGA_GPIO_DEBUG_3)

#define GARCIA_GPIO_IRQ_MASK (GARCIA_GPIO_INPUTS_MASK)

#define GARCIA_FPGA_GPIO_MASK (GARCIA_GPIO_INPUTS_MASK)

#endif /* GARCIA_FPGA_PRIV_H_ */
