#
# Makefile for the LabX Garcia Snake board
#

# Include Xilinx common definitions and Lab X AVB headers
EXTRA_CFLAGS += -I$(TOPDIR)/drivers/xilinx_common

# Include the Garcia-specific drivers
obj-y += garcia_control.o
obj-y += garcia_fpga.o

