/*
 * garcia_fpga_priv.h
 *
 *  Created on: Jan 25, 2011
 *      Author: swagner
 */
#ifndef GARCIA_FPGA_PRIV_H_
#define GARCIA_FPGA_PRIV_H_

#include <linux/garcia_fpga.h>

#define GARCIA_FPGA_GPIO_REGISTER	0x00
#define GARCIA_FPGA_GPIO_GIER		0x47*4
#define GARCIA_FPGA_GPIO_IPIER		0x4A*4
#define GARCIA_FPGA_GPIO_IPISR		0x48*4

#define GARCIA_FPGA_GPIO_GIE		0x80000000
#define GARCIA_FPGA_GPIO_IPIE		0x1

#define GARCIA_FPGA_GPIO_ALL_MUTE (GARCIA_FPGA_GPIO_SLOT_MUTE_1 | \
	GARCIA_FPGA_GPIO_SLOT_MUTE_2 | GARCIA_FPGA_GPIO_SLOT_MUTE_3 | \
	GARCIA_FPGA_GPIO_SLOT_MUTE_4 | GARCIA_FPGA_GPIO_SLOT_MUTE_5)
#define GARCIA_FPGA_GPIO_ALL_RESET (GARCIA_FPGA_GPIO_SLOT_RESET_1 | \
	GARCIA_FPGA_GPIO_SLOT_RESET_2 | GARCIA_FPGA_GPIO_SLOT_RESET_3 | \
	GARCIA_FPGA_GPIO_SLOT_RESET_4 | GARCIA_FPGA_GPIO_SLOT_RESET_5)
#define GARCIA_FPGA_GPIO_ALL_SSI_DDIR (GARCIA_FPGA_SLOT_SSI_DDIR_1 | \
	GARCIA_FPGA_SLOT_SSI_DDIR_2 | GARCIA_FPGA_SLOT_SSI_DDIR_3 | \
	GARCIA_FPGA_SLOT_SSI_DDIR_4 | GARCIA_FPGA_SLOT_SSI_DDIR_5)
#define GARCIA_FPGA_GPIO_ALL_SPISEL (GARCIA_FPGA_GPIO_SLOT_SPISEL_1 | \
	GARCIA_FPGA_GPIO_SLOT_SPISEL_2 | GARCIA_FPGA_GPIO_SLOT_SPISEL_3 | \
	GARCIA_FPGA_GPIO_SLOT_SPISEL_4 | GARCIA_FPGA_GPIO_SLOT_SPISEL_5)

#define GARCIA_GPIO_INPUTS_MASK ( \
	GARCIA_FPGA_GPIO_BOX_ID_MASK | GARCIA_FPGA_GPIO_PUSHBUTTON | GARCIA_FPGA_GPIO_PWRFAIL | \
	GARCIA_FPGA_GPIO_JUMPER_1 | GARCIA_FPGA_GPIO_JUMPER_2 | GARCIA_FPGA_GPIO_DEBUG_0 | \
	GARCIA_FPGA_GPIO_DEBUG_1 | GARCIA_FPGA_GPIO_DEBUG_2 | GARCIA_FPGA_GPIO_DEBUG_3)

#define GARCIA_GPIO_IRQ_MASK (GARCIA_GPIO_INPUTS_MASK | GARCIA_FPGA_GPIO_ALL_SPISEL)

#define GARCIA_FPGA_GPIO_MASK (GARCIA_GPIO_INPUTS_MASK | GARCIA_FPGA_GPIO_ALL_MUTE | \
	GARCIA_FPGA_GPIO_ALL_RESET | GARCIA_FPGA_GPIO_ALL_SPISEL)

#endif /* GARCIA_FPGA_PRIV_H_ */
